apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap-es-syncer.fullname" . }}
  labels:
    {{- include "ldap-es-syncer.labels" . | nindent 4 }}
type: Opaque
data:
  LDAP_PASSWORD: {{ .Values.ldap.password | b64enc | quote }}
  ELASTIC_PASSWORD: {{ .Values.elasticsearch.password | b64enc | quote }}
